:: Generated by KSST64 v2.1
@echo off
cd /d %~dp0
if not defined PYTHONHOME (
	echo not define 'PYTHONHOME' envionment variable, please install python and define it
	pause
	exit
)
set path=%path%;%PYTHONHOME%;%PYTHONPATH%
for /f "tokens=1,2*" %%i in ("gdb.exe aarch64-linux-android-gdb.exe") do (
	if exist %%~$path:i (
		%%~$path:i -q -w -x scrutils/init.gdb
		exit
	)
	if exist %%~$path:j (
		%%~$path:j -q -w -x scrutils/init.gdb
		exit
	)
)
echo Not exist gdb, please install NDK and add file path to $PATH envionment variable
pause